sudo: required
dist: trusty
addons:
  artifacts:
    paths:
      - results
  apt:
    sources:
      - google-chrome
    packages:
      - google-chrome-stable
language: node_js
node_js:
  - '7'
cache:
  directories:
    - node_modules
    - bower_components
    - $HOME/.npm
    - $HOME/.cache
before_script:
  - npm install
before_deploy:
  - npm run build
env:
  global:
    - NODE_ENV=testing
    - ARTIFACTS_BUCKET=js-tasks-ru
    - secure: >-
        b/9ns2ap8y3fVDtMPjK30KC4E6z5BkdIsYj1HKRDdwhvibnV5Vart7U7Rq6sxgimpNI6enK07qSOpCNm32OpgpNXYULmm6ejsBIHeJaymmhtBwSFqm4ZErVXGsM/MJ4kmgUbUMHSi8g1lm2d/CpYX1F8zZLtHYcE3W62sbkHGnChuT3qUwSvE7fU++WAMOjKKeMB2bwHtxD4C4gN9nwdrW2aGG3ff9gmsCOnKBrR/QR3mht7hdtkGiou3xKe5C0VtS5hvNWENx1L3KBHEQIEtFR9zSMPWc2Ok6OTV4jzYDHtHeNYGMOn6vGZYg3GU9y1TJVDeqBjX0Xt+9AtbbBeJBSoEKKF+oUfT/6hScGGGPtLhwOKBp7askPIKEQeRbaFJaYKofAsOJe2LNnaiKNC2aC2rjWKAxH5bRqwEbxuXiQI/0DM/fiY3x6aZ39ZJwGywtXDoBr2xCSzvUjiHbpRp4nfQJW/lAoLlMPITxxTqBdbMst3ZavJZAf/xjya/tN11cbjxQhu7MBKUGrf7AYOEB7/1jMLJ5As+EHoTBK47AJNAXaVPModt0hHm9ixd5D/W9cbcrmw9+z/8JzCCafwiB0uLgG/KDheb7Y/0tUwBIGPIbMKXtwNV12Jf8HcGV0aO8lh5kXlsydqExnXm8g02YWPjipL5GwA6RuxzvZBKMo=
    - secure: >-
        IfGEhb3+pxBH7I8996UKpWt34KcQmRF7kni4rWcdDsxFop/mzow0uVkCH5vHKxb/sIX6Bdsi7NkmOzlCwjN8JyC9ZaQ/MeJXOR1yjwUIhKQPPrR37McoM4SwSc4D7kEWcVg3ceBTK1A39uh6DD8qSGbNoAo/GR+zErbl8Z8PbgkWJ7F+d+H46q6koZ4D5QwWsrYqPvHefDsi9VfM6dP7WwrBxIKwRgomzKErJY3WECFF9AF8nu8hdpLtr9/iyi0OnUQwfbeYATc6bA1kLQPSY6njAaqUcv3JouQQnWBGJ8+qUk/hjPR0N/bSUumRxBNXPUoPJhBJz2XjQE03Bn0VFJsVlMLFZ/Q8qpimPhwWhCF8Yb/bB9x+VOuQZlZjBBiIRp6TQicqLQ5980ASPaTKJZ2C+JnKGsZBz/xMNs9aHVLg13joOMkE/I33v8aFrL74wj24yQHQ/kx3BWMChWq6+i0Y0/MMVXYhW0jGO86v0flCkSujlFmpjg/bgjsryHQFX77zdml+GXtX3mKdB7P7/GS4xvBepevf4m82azTtTt5g/hqeztfndD+tB+ot10JiKrcjneIB/tv3xB2wYd3PjhnRBrzTJeQebZ8X/bauVbOR6bejZeEgpqyMfIJHdIDRSqKREtVKHC3SDXGzZyWix3BTwFR4bXCq77+7d4lhnv8=
script:
  - npm run test
notifications:
  webhooks: 'http://learn.javascript.ru/automation/ci/build'
